### PR TITLE
chore: Refactor UUID generation

### PR DESCRIPTION
**Pull request by cbrea**
Change UUID generation method by a more unpredictable approach

### CODE REVIEW

**Review by mbenitod — APPROVED** [review]
LGTM

**Review by mariolg — COMMENTED** [review]
Have a look at other constructions as:

```
uuid.New().String()
uuid.NewString()
```

Just to check their also implementing version 4 of UUID, as `NewUUID` does.

**Comment by cbrea** [comment]
> 
> 
> Have a look at other constructions as:
> 
> ```
> uuid.New().String()
> uuid.NewString()
> ```
> 
> Just to check their also implementing version 4 of UUID, as `NewUUID` does.

We could asssume these methods as is due internally are invoking NewRandom()
[DOC](https://github.com/google/uuid/blob/v1.2.0/version4.go#L13)

**Review by mariolg — APPROVED** [review]
LGTM

**Pull request merged**
